// VOLT — dark-first palette (Voltage default). Token names are stable across
// palettes; flipping `palette` should recolor the whole app.

const voltage = {
  bg: '#0A0C10',
  bgAlt: '#11141A',
  surface: '#161A21',
  surface2: '#1C212B',
  line: '#262C37',
  lineSoft: '#1E232C',
  text: '#F5F7FA',
  textMute: '#8E96A4',
  textDim: '#5A6271',
  accent: '#D4FF3D',
  accentDark: '#B8E034',
  accent2: '#FF5C3A',
  accent3: '#5BE0FF',
};

export const palettes = {
  voltage,
  magma: {
    bg: '#120A0A',
    bgAlt: '#1F1414',
    surface: '#1F1414',
    surface2: '#2A1A1A',
    line: '#3A2424',
    lineSoft: '#2A1818',
    text: '#FFF5F0',
    textMute: '#B59689',
    textDim: '#6E574E',
    accent: '#FF4438',
    accentDark: '#D43A2E',
    accent2: '#FFB833',
    accent3: '#FFE26B',
  },
  subzero: {
    bg: '#08111A',
    bgAlt: '#102132',
    surface: '#102132',
    surface2: '#143046',
    line: '#1F3A56',
    lineSoft: '#172A3F',
    text: '#F0F7FF',
    textMute: '#8AA6BC',
    textDim: '#52708A',
    accent: '#5BE0FF',
    accentDark: '#3FB8D4',
    accent2: '#FFB833',
    accent3: '#FF5C9C',
  },
  paper: {
    bg: '#F4F1EA',
    bgAlt: '#FFFFFF',
    surface: '#FFFFFF',
    surface2: '#EDEAE1',
    line: '#D7D2C5',
    lineSoft: '#E5E0D4',
    text: '#1A1A1A',
    textMute: '#5B5B58',
    textDim: '#9B9B96',
    accent: '#0E5B3B',
    accentDark: '#094A30',
    accent2: '#E04634',
    accent3: '#1A1A1A',
  },
};

const active = voltage;

export const colors = {
  // VOLT semantic tokens (preferred for new code)
  bg: active.bg,
  bgAlt: active.bgAlt,
  surface: active.surface,
  surface2: active.surface2,
  line: active.line,
  lineSoft: active.lineSoft,
  text: active.text,
  textMute: active.textMute,
  textDim: active.textDim,
  accent: active.accent,
  accentDark: active.accentDark,
  accent2: active.accent2,
  accent3: active.accent3,

  // Back-compat aliases mapped to VOLT roles
  bgDark: active.bg,
  bgDarkAlt: active.bgAlt,
  surfaceMuted: active.bg,
  surfaceCard: active.surface,
  textPrimary: active.text,
  textSecondary: active.textMute,
  textMuted: active.textDim,
  textOnDark: active.text,
  textOnDarkMuted: 'rgba(245,247,250,0.6)',
  textOnAccent: '#0A0C10',
  accentTeal: active.accent2,
  accentTealLight: active.accent3,
  divider: active.lineSoft,
  divederStrong: active.line,
  like: active.accent2,
  overlay: 'rgba(0,0,0,0.65)',
  shadow: '#000000',
  white: '#FFFFFF',
  black: '#000000',
};
